error: avoid leaking ring::error::KeyRejected into api
Having `From<ring::error::KeyRejected>` defined on the public `Error`
type means that the `*ring*` type leaks into rcgen's public API,
complicating semver incompatible updates.

This commit takes the simple approach of using the crate-internal
`ExternalError` trait to convert from the `*ring*` error type to our
generic rcgen `Error::RingKeyRejected` type as needed. This allows the
`From` impl on `Error` to be removed, fixing the type leak.